name: '🎛️ Atualizar Versão'
description: 'Atualiza a versão no package.json e realiza um commit.'
inputs:
  version:
    description: 'Nova versão para ser definida no package.json.'
    required: true
  version_semantic:
    description: 'Versão semântica para ser apresentada.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🚚 Checkout Project
      uses: actions/checkout@v3

    - name: 📝 Show package.json
      run: cat package.json
      shell: bash

    - name: Verificar versão
      run: |
        git pull
        CURRENT_VERSION=$(jq -r '.version' package.json)
        echo "Versão atual: $CURRENT_VERSION"
        if [ "$CURRENT_VERSION" == "${{ inputs.version }}" ]; then
          echo "Versão atual já é $CURRENT_VERSION. Nenhuma atualização necessária."
          echo "skip_commit=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: 📝 Update Version
      if: env.skip_commit != 'true'
      run: |
        echo "Atualizando versão para ${{ inputs.version }}"
        jq '.version = "${{ inputs.version }}"' package.json > temp.json && mv temp.json package.json
      shell: bash

    - name: Commit
      if: env.skip_commit != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add package.json
        git commit -m "RELEASE-$VERSION_SEMANTIC"
        
        git push
        echo "Versão atualizada para $VERSION"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        VERSION_SEMANTIC: ${{ inputs.version_semantic }}
