name: '🚀 Processo Completo de Release do Módulo'
description: 'Executa todos os passos necessários para o release de um módulo, incluindo obtenção da versão, configuração de variáveis de ambiente, validação e atualização de versão.'
inputs:
  release_branch:
    description: 'Branch de release para a qual a versão será incrementada.'
    required: false
    default: 'main'
  module:
    description: 'Módulo a ser lançado.'
    required: true
  actual_branch:
    description: 'Branch atual do repositório.'
    required: true

outputs:
  now:
    description: 'Data e hora atual.'
    value: ${{ steps.setup_env_vars.outputs.now }}
  version:
    description: 'A próxima versão do projeto.'
    value: ${{ steps.get_and_check_version.outputs.version }}
  version_semantic:
    description: 'Versão semântica para ser apresentada.'
    value: ${{ steps.setup_env_vars.outputs.version_semantic }}
  archive_name:
    description: 'Nome do arquivo de release.'
    value: ${{ steps.setup_env_vars.outputs.archive_name }}
  release_branch:
    description: 'Branch de release para a qual a versão será incrementada.'
    value: ${{ steps.setup_env_vars.outputs.release_branch }}
  module:
    description: 'Módulo a ser lançado.'
    value: ${{ inputs.module }}
  folder:
    description: 'Pasta onde o release será lançado.'
    value: ${{ steps.setup_env_vars.outputs.folder }}
  module_name:
    description: 'Nome do módulo em caixa alta.'
    value: ${{ steps.setup_env_vars.outputs.module_name }}
  
runs:
  using: 'composite'
  steps:
    - name: Obter e Verificar Versão
      id: get_and_check_version
      uses: Endems/workflows/get-and-check-version@teste
      with:
        release_branch: ${{ inputs.release_branch }}

    - name: Configurar Variáveis de Ambiente
      id: setup_env_vars
      uses: Endems/workflows/setup-env-vars@teste
      with:
        version: ${{ steps.get_and_check_version.outputs.version }}
        release_branch: ${{ inputs.release_branch }}
        module: ${{ inputs.module }}

    - name: Validar Variáveis de Ambiente
      uses: Endems/workflows/check-env-vars@teste
      with:
        now: ${{ steps.setup_env_vars.outputs.now }}
        version: ${{ steps.setup_env_vars.outputs.version }}
        version_semantic: ${{ steps.setup_env_vars.outputs.version_semantic }}
        release_branch: ${{ steps.setup_env_vars.outputs.release_branch }}
        archive_name: ${{ steps.setup_env_vars.outputs.archive_name }}
        module: ${{ steps.setup_env_vars.outputs.module }}
        folder: ${{ steps.setup_env_vars.outputs.folder }}
        module_name: ${{ steps.setup_env_vars.outputs.module_name }}

    - name: Atualizar Versão
      uses: Endems/workflows/update-version@teste
      with:
        version: ${{ steps.setup_env_vars.outputs.version }}
        version_semantic: ${{ steps.setup_env_vars.outputs.version_semantic }}

    