name: '游 Processo Completo de Release do M칩dulo'
description: 'Executa todos os passos necess치rios para o release de um m칩dulo, incluindo obten칞칚o da vers칚o, configura칞칚o de vari치veis de ambiente, valida칞칚o e atualiza칞칚o de vers칚o.'
inputs:
  release_branch:
    description: 'Branch de release para a qual a vers칚o ser치 incrementada.'
    required: false
    default: 'main'
  module:
    description: 'M칩dulo a ser lan칞ado.'
    required: true
  actual_branch:
    description: 'Branch atual do reposit칩rio.'
    required: true

outputs:
  version:
    description: 'A pr칩xima vers칚o do projeto.'
  version_semantic:
    description: 'Vers칚o sem칙ntica para ser apresentada.'
  archive_name:
    description: 'Nome do arquivo de release.'

runs:
  using: 'composite'
  steps:
    - name: Obter e Verificar Vers칚o
      id: get_and_check_version
      uses: Endems/workflows/get-and-check-version@teste
      with:
        release_branch: ${{ inputs.release_branch }}

    - name: Configurar Vari치veis de Ambiente
      id: setup_env_vars
      uses: Endems/workflows/setup-env-vars@teste
      with:
        version: ${{ steps.get_and_check_version.outputs.version }}
        release_branch: ${{ inputs.release_branch }}
        module: ${{ inputs.module }}

    - name: Validar Vari치veis de Ambiente
      uses: Endems/workflows/check-env-vars@teste
      with:
        now: ${{ steps.setup_env_vars.outputs.now }}
        version: ${{ steps.setup_env_vars.outputs.version }}
        version_semantic: ${{ steps.setup_env_vars.outputs.version_semantic }}
        release_branch: ${{ steps.setup_env_vars.outputs.release_branch }}
        archive_name: ${{ steps.setup_env_vars.outputs.archive_name }}
        module: ${{ steps.setup_env_vars.outputs.module }}

    - name: Atualizar Vers칚o
      uses: Endems/workflows/update-version@teste
      with:
        version: ${{ steps.setup_env_vars.outputs.version }}
        version_semantic: ${{ steps.setup_env_vars.outputs.version_semantic }}

    